version: '3.8'

services:
  app:
    container_name: recrutement_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DATABASE_URL: "pgsql://postgres:0000@db:5432/recrutement_app"
    working_dir: /var/www/html

  db:
    image: postgres:15
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: recrutement_app
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
